name: hse_chat
description: A chat for hse courses

version: 1.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  riverpod: ^1.0.3
  flutter_riverpod: ^1.0.3
  hooks_riverpod: ^1.0.3
  dio: ^4.0.6
  freezed: ^1.1.1
  freezed_annotation: ^1.1.0
  flutter_hooks: ^0.18.3
  cupertino_icons: ^1.0.2

  firebase_storage: ^10.2.11
  firebase_auth: ^3.3.13
  firebase_core: ^1.14.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.4
  build_runner: ^2.1.8
  json_serializable: ^6.1.5

flutter:
  uses-material-design: true
